apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readers
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readers-rolebinding
subjects:
- kind: ServiceAccount
  name: nginx-serviceaccount
  apiGroup: ""
roleRef:
  kind: Role
  name: readers
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-serviceaccount
---
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
spec:
  serviceAccountName: nginx-serviceaccount
  containers:
  - name: nginx-container
    image: nginx
  - name: proxy
    image: bitnami/kubectl:latest
    args: ["proxy", "--port=8000"]