# Spring properties
springProfile: compose

# Service properties
services:
  ui:
    replicas: 2
    type: LoadBalancer
    resources:
      requests: 500m
      limits: 500m
  productApi:
    replicas: 2
    resources:
      requests: 500m
      limits: 500m
  orderApi:
    replicas: 2
    resources:
      requests: 500m
      limits: 500m
  gateway:
    replicas: 2
    type: LoadBalancer
    resources:
      requests: 500m
      limits: 700m
  authApi:
    replicas: 2
    
  ingress:
    type: LoadBalancer