apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rvstore-ingress
  namespace: rvstore
spec:
  ingressClassName: nginx
  rules:
  - host: localhost #demo.localdev.me
    http:
      paths:
      - backend:
          service:
            name: rvstore-ui
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: rvstore-product-api
            port:
              number: 9001
        path: /products
        pathType: Prefix
      - backend:
          service:
            name: rvstore-order-api
            port:
              number: 9002
        path: /orders
        pathType: Prefix
      - backend:
          service:
            name: rvstore-auth-api
            port:
              number: 9003
        path: /auth
        pathType: Prefix
      - backend:
          service:
            name: elasticsearch
            port:
              number: 9200
        path: /products/_search
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: localhost
