apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: rvstore
spec:
  replicas: 1
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.13.4 #public.ecr.aws/vergeops/rvstore-elasticsearch:latest
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: http.cors.allow-origin
          value: "*"
        - name: http.cors.enabled
          value: "true"
        - name: http.cors.allow-headers
          value: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        - name: http.cors.allow-credentials
          value: "true"
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: rvstore
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200