apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: vergeops/k8s-rvstore-ui:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
  labels:
    app: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: rvstore-product-api
        image: vergeops/k8s-rvstore-product-api:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config
        ports:
        - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /products/
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: rvstore-order-api
        image: vergeops/k8s-rvstore-order-api:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config
        ports:
        - containerPort: 9002
        readinessProbe:
          httpGet:
            path: /orders
            port: 9002
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-simulator-deployment
  labels:
    app: order-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-simulator
  template:
    metadata:
      labels:
        app: order-simulator
    spec:
      containers:
      - name: rvstore-order-simulator
        image: vergeops/k8s-rvstore-order-simulator:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: rvstore-api-gateway
        image: vergeops/k8s-rvstore-api-gateway:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
