apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout-with-analysis.yaml
- analysis-success-rate.yaml
- ../canary/canary-service.yaml
- ../canary/canary-ingress.yaml
- ../canary/canary-preview-service.yaml
- ../canary/canary-preview-ingress.yaml
